import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router';
import { ArrowUpRight, RefreshCw, Wallet } from 'lucide-react';
import { api, ApiError } from './lib/api';
import { Button } from './components/ui/button';
type Position = { conid: number; contractDesc: string; assetClass?: string | null; position: number; currency: string; mktPrice?: number | null; mktValue?: number | null; avgCost?: number | null; unrealizedPnl?: number | null };
type Portfolio = { status: 'not_configured' } | { status: 'connected'; accountId: string; fetchedAt: string; positions: Position[] };
const number = (value: number | null | undefined) => value == null ? '—' : new Intl.NumberFormat('es-ES', { maximumFractionDigits: 4 }).format(value);
export function Growth() {
  const [search, setSearch] = useState('');
  const portfolio = useQuery({ queryKey: ['growth'], queryFn: () => api<Portfolio>('/finance/growth'), retry: false });
  const data = portfolio.data?.status === 'connected' ? portfolio.data : undefined;
  const positions = data?.positions.filter(p => `${p.contractDesc} ${p.assetClass ?? ''} ${p.currency}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  return <div className="growth-page">
    <p className="eyebrow">FINANZAS / GROWTH</p>
    <div className="growth-heading"><div><h1>Growth</h1><p className="text-muted-foreground mt-2">Tus inversiones, en un solo lugar.</p></div><Button variant="outline" disabled={portfolio.isFetching} onClick={() => portfolio.refetch()}><RefreshCw size={16} className={portfolio.isFetching ? 'animate-spin' : ''}/>{portfolio.isFetching ? 'Actualizando…' : 'Actualizar'}</Button></div>
    <section className="broker-card"><div className="broker-mark"><Wallet size={24}/></div><div><h2 className="font-semibold">Interactive Brokers</h2><p className="text-sm text-muted-foreground">{data ? `Cuenta ${data.accountId} · Solo lectura` : 'Tu cartera de inversión'}</p></div><span className="broker-status">{portfolio.isError ? 'Sin conexión' : data ? 'Conectado' : 'Pendiente de conexión'}</span></section>
    {portfolio.isPending ? <div className="portfolio-state" role="status">Cargando tus posiciones…</div> : portfolio.isError ? <div className="portfolio-state" role="alert"><h2>No se han podido cargar las posiciones</h2><p>{portfolio.error.message}</p>{portfolio.error instanceof ApiError && portfolio.error.status === 401 && <Link to="/" className="underline">Volver a iniciar sesión</Link>}</div> : portfolio.data?.status === 'not_configured' ? <div className="portfolio-state"><div className="state-icon"><ArrowUpRight size={28}/></div><h2>Conecta tu cuenta de Interactive Brokers</h2><p>Cuando esté configurada la conexión, aquí verás tus posiciones y su valoración.</p><ol><li>Activar el Client Portal Gateway e iniciar sesión en Interactive Brokers.</li><li>Vincular tu cuenta de IBKR con tu usuario de esta app.</li><li>Actualizar esta pantalla para consultar tus posiciones.</li></ol><p className="text-sm">La conexión se configura en el servidor. No necesitas introducir tu contraseña de IBKR en esta app.</p></div> : data && <section className="positions-panel"><div className="positions-toolbar"><div><h2>Posiciones <span>{data.positions.length}</span></h2><p className="text-sm text-muted-foreground">Última consulta: {new Date(data.fetchedAt).toLocaleString('es-ES')}</p></div><div><label htmlFor="position-search" className="sr-only">Buscar posiciones</label><input id="position-search" type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar activo o divisa…"/></div></div>{!data.positions.length ? <div className="portfolio-state"><h2>No tienes posiciones abiertas</h2><p>Interactive Brokers no ha devuelto posiciones para esta cuenta.</p></div> : !positions.length ? <p className="p-8" role="status">No hay posiciones que coincidan con tu búsqueda.</p> : <div className="table-scroll"><table><caption className="sr-only">Posiciones en Interactive Brokers</caption><thead><tr>{['Activo', 'Tipo', 'Cantidad', 'Precio', 'Coste medio', 'Valor de mercado', 'P/G no realizada', 'Divisa'].map(title => <th scope="col" key={title}>{title}</th>)}</tr></thead><tbody>{positions.map((p, index) => <tr key={`${p.conid}-${index}`}><td className="font-semibold">{p.contractDesc}</td><td>{p.assetClass ?? '—'}</td><td>{number(p.position)}</td><td>{number(p.mktPrice)}</td><td>{number(p.avgCost)}</td><td>{number(p.mktValue)}</td><td className={(p.unrealizedPnl ?? 0) < 0 ? 'text-red-700' : (p.unrealizedPnl ?? 0) > 0 ? 'text-emerald-700' : ''}>{number(p.unrealizedPnl)}</td><td>{p.currency}</td></tr>)}</tbody></table></div>}<p className="p-5 text-xs text-muted-foreground">Importes en la divisa de cada posición. La valoración puede tener retraso; la hora indica cuándo se consultó IBKR.</p></section>}
  </div>;
}
